### ISSUE TITLE
Update installation instructions to include installation through the library manager

### ISSUE THREAD

**Issue by JobLeonard** [joelmoniz/Git-Manager#1]
First: thanks for this! Giving it a spin, I hope it will make using Git easier for newbies.

Anyway, I discovered it through the library manager of Processing 3.0b6. It installed just fine, but after that it didn't appear to work at first. *However*, the issue was simply that I had to restart processing.

Maybe you want to mention that in the installation blurb in the library manager? And also mention in the readme file here that you can install the Git Manager through the built-in library manager.

**Comment by joelmoniz** [comment]
Thanks for the bug report! It's actually a little surprising that you managed to get it working in Processing 3.06b at all ( I wasn't able to). The issue was that the Base class was broken down in 3.0b4, which breaks the Git Manager's compatibility with any release after that. I've updated everything now, and a restart after install is no longer required in the latest version of Git Manager. Could you check out the latest version, and re-open this issue if everything is not alright?

I've also updated the readme file to mention installing the Git Manager via the library manager.

**Comment by JobLeonard** [comment]
Well, I got the GUI window to show up and not much else :p. Will try out the new version and report back as soon as I got my laptop again (travelling light now)
